sync: use correct SSL context for HTTPS fetching
ssl.Purpose.CLIENT_AUTH is for acting as a _server_:
"Option for create_default_context() and SSLContext.load_default_certs().
This value indicates that the context may be used to authenticate web clients
(therefore, it will be used to create server-side sockets)."

This has caused failures in the pkgcheck CI/github action:
https://github.com/gentoo/guru/runs/4456586656?check_suite_focus=true#step:3:113

... like:
```
    File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/urllib/request.py", line 1351, in do_open
      raise URLError(err)
  urllib.error.URLError: <urlopen error Cannot create a client socket with a PROTOCOL_TLS_SERVER context (_ssl.c:801)>
[...]
    File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/pkgcore/sync/http.py", line 55, in _sync
      if e.getcode() == 304: # Not Modified
  AttributeError: 'URLError' object has no attribute 'getcode'
Error: The process '/opt/hostedtoolcache/Python/3.10.0/x64/bin/pmaint' failed with exit code 1
```

Signed-off-by: Sam James <sam@gentoo.org>
Closes: https://github.com/pkgcore/pkgcore/pull/332